### ISSUE TITLE
Improve code-structure

### ISSUE THREAD

**Issue by raphaelschwinger** [DBD-research-group/BirdSet#40]
Improve to code structure so that:
- all source code is in `/src` (coding convention)
- it aligns with lightning-hydra-template and yet-another-lightining-template
- the package can be (in the future) added to pip
- be now loaded easily in other repos through tools (e.g. poetry)

## Todos

- [x] improve folder structure (see Readme.md)
- [ ] make experiments runnable
    - [x] add `train.py` from lightning-hydra-template. We can still use a custom train function, if needed, but we should use their config structure to be able to share code easily
    - [ ] remove feature_extractor form datamodule as it should be connected to the model
    - [ ] train resnet18 on esc50
    - [ ] log on wandb
    - [ ] finetune ast on esc50
    - [ ] finetune w2v2 on esc50
- [ ] check out W&B
- [ ] Write docs
  - [ ] How to run experiments
  - [ ] What to do for new experiments
