### ISSUE TITLE
Train EAT

### ISSUE THREAD

**Issue by raphaelschwinger** [DBD-research-group/BirdSet#63]
Train EAT on HSN dataset

## Todos

- [x] Interegate code
- [x] Run without augmentations on ESC50
- [x] train on M without augmentations, compare to ResNet
- [ ] Integrate their augmentations
  - [x] amp
  - [x] neg
  - [x] tshift
  - [ ] tmask: Not present in torch-audiomentations, adding it in our repo is difficult since we can not use torch-audiomentations test code -> [forked the repo](https://github.com/raphaelschwinger/torch-audiomentations/tree/add-time-masking) ; currently learning how to do the augmentation in parallel in the batch and on the gpu, I guess that's important for speed...
  - [ ] ampsegment
  - [ ] cycshift
- [ ] augs_noise
- [ ] augs_mix
- [x] Eval on HSN test
