### ISSUE TITLE
Add simple docs

### ISSUE THREAD

**Issue by raphaelschwinger** [DBD-research-group/BirdSet#73]
# TODO

- [x] README.md
- [x] base_datamodule
   - [x] refactor to use `@dataclass` instead of `DictConfig` 
   - [x] test Hydra config by calling  from `main.py`
   - [x] test overriding from python without hydra (important for using as package)
   - [x] comment base_datamodule
   - [x] comment `transforms`
   - [x] comment `augmentations`
   - [x] comment `resize`
   - [x] comment `feature_extraction`
   - [x] notebook to test it
   - [x] sync README and Notion page
- [ ] base_module
